branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
before_script:
- echo OSS_KEY=$OSS_KEY >> .env
- echo OSS_SECRET=$OSS_SECRET >> .env
- echo OSS_BUCKET=$OSS_BUCKET >> .env
- echo OSS_REGION=$OSS_REGION >> .env
script:
- ./build.sh
after_success:
- GREN_GITHUB_TOKEN=$GITHUB_TOKEN yarn release
- sleep 3 && ./notify.sh
cache: yarn
deploy:
- provider: pages
  local-dir: docs
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
- provider: npm
  email: levy9527@qq.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
